blog/urls.py
from django.views.generic import ListView
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

"""
Мы определили пространство имен приложения в переменной 'app_name'.
Это позволит нам сгруппировать адреса
для приложения блога и использовать их названия для доступа к ним.
"""

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    
    # standart pagination
    # path('', views.PostListView.as_view(), name='post_list'),
]

index/urls.py
from django.views.generic import ListView
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    # post views
    path('', views.index, name='asosiy'),
    # path('menu/<int:pk>/', views.get_menu, name='menu'),
    
]

site13/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from index.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('index/', include('index.urls', namespace='index')),
    
    path('', include('index.urls', namespace='index')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

app_name = 'blog'

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    image = models.ImageField(upload_to='blog/%Y/%m/%d', blank=True, default='blog/no_image.png')
    views = models.IntegerField(default=0, verbose_name='Views')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    tags = TaggableManager()
    objects = models.Manager()     # Менеджер по умолчанию.
    published = PublishedManager() # Наш новый менеджер.

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month,
        											self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity

# standart pagination
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 1
#     template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):

    title = "Yangiliklar"
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # По 3 статьи на каждой странице.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/blog.html', locals())

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug = post, status = 'published', publish__year = year,
    							publish__month = month, publish__day = day)

    post.views += 1
    post.save()

    last_posts = Post.objects.order_by("-publish")[:3]
    all_tags = Tag.objects.all()
    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)

    new_comment = None
    comment_form = CommentForm()
    if request.method == 'POST':
        # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
        else:
            comment_form = CommentForm()

    # Формирование списка похожих статей.
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]

    return render(request, 'blog/post/blog-details.html', locals() )

def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    form = ''
    if request.method == 'POST':
        # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию.
            cd = form.cleaned_data
            # Отправка электронной почты.
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'. \
            	format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET: 
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        
  		# В этом примере мы применяем векторы по полям title и body с разным весом.
  		# По умолчанию используются веса D, C, B и A, которые соответствуют числам 0.1, 0.2, 0.4 и 1.
  		# Мы применили вес 1.0 для вектора по полю title и 0.4 – для вектора по полю body.
  		# В конце отбрасываем статьи с низким рангом и показываем только те, чей ранг выше 0.3.
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        # results = Post.objects.annotate( rank=SearchRank(search_vector, search_query)) \
        # 			.filter(rank__gte=0.3).order_by('-rank')
        # pg_trgm PostgreSQL rasshireniyani o'rnatish kerak TrigramSimilarity uchun --- CREATE EXTENSION pg_trgm
        results = Post.objects.annotate( similarity=TrigramSimilarity('title', query),) \
        			.filter(similarity__gt=0.3).order_by('-similarity')

    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

templates/blog/post/blog-details.html
{% extends "index/index.html" %}
{% load blog_tags %}

    {% block title %}{{ post.title }}{% endblock %}

    {% block content %}

        <!--Breadcrumb Banner Area Start-->
        <div class="breadcrumb-banner-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="breadcrumb-text">
                            <h1 class="text-center">Batafsil</h1>
                            <div class="breadcrumb-bar">
                                <ul class="breadcrumb text-center">
                                    <li><a href="{% url 'index:asosiy' %}">Bosh sahifa</a></li>
                                    <li><a href="{% url 'blog:post_list' %}">Yangiliklar</a></li>
                                    <li>Batafsil</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--End of Breadcrumb Banner Area-->
        <!--News Details Area Start-->
        <div class="news-details-area section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12 col-12">
                        <div class="news-details-content">
                           <div class="single-latest-item">
                                <img src="/media/{{ post.image }}" alt="{{ post.title }}" width="870" height="440">  
                                <div class="single-latest-text">
                                    <h3>{{ post.title }}</h3> 
                                    <div class="single-item-comment-view">
                                       <span><i class="zmdi zmdi-calendar-check"></i>{{ post.publish|date:"d.m.Y" }}</span>
                                        <span><i class="zmdi zmdi-eye"></i>{{ post.views }}</span>
                                        <span><i class="zmdi zmdi-comments"></i>
                                            {# commentlar soni #}
                                            {{ comments.count }}
                                        </span>
                                    </div>        
                                    {{ post.body|markdown }}
                                    <div class="tags-and-links">
                                        <div class="related-tag">
                                            <span>Tag:</span>
                                            <ul class="tags">
                                                {% for tag in post.tags.all %}
                                                    <li>
                                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                                            {{ tag.name }}
                                                        </a>
                                                        {% if not forloop.last %}, {% endif %}
                                                    </li>                     
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        <div class="social-links">
                                            <span>Share:</span>
                                            <a href="#"><i class="zmdi zmdi-facebook"></i></a>
                                            <a href="#"><i class="zmdi zmdi-twitter"></i></a>
                                            <a href="#"><i class="zmdi zmdi-google-old"></i></a>
                                            <a href="#"><i class="zmdi zmdi-instagram"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="comments">
                                <h4 class="title">Comments</h4>
                                {# comment #}
                                {% for comment in comments %}
                                    {# comment-reply #}
                                    <div class="single-comment">
                                        <div class="author-image">
                                            <img src="/media/blog/no_image.png" alt="no_image">
                                        </div>
                                        <div class="comment-text">
                                            <div class="author-info">
                                                <h4><a href="#">{{ comment.name }}</a></h4>
                                                <span class="reply"><a href="#">Reply</a></span>
                                                <span class="comment-time">Posted on {{ comment.created|date:"H-m d.m.Y" }} /</span>
                                            </div>
                                            <p>{{ comment.body|linebreaks }}</p>
                                        </div>
                                    </div>
                                    {% empty %}
                                    <p>There are no comments yet.</p>
                                {% endfor %}
                                {# end comment #}
                                <h2>Add a new comment</h2>
                                <form action="." method="post">
                                    {{ comment_form.as_p }}
                                    {% csrf_token %}
                                    <p><input type="submit" value="Add comment"></p>
                                </form>
                            </div>
                        </div>    
                    </div>
                    <div class="col-lg-3 col-md-12 col-12">
                            <div class="sidebar-widget">
                                {% if similar_posts %}
                                    <div class="single-sidebar-widget">
                                        <h4 class="title">Similar Posts</h4>
                                        <div class="recent-content">
                                            {% for tag in similar_posts %}
                                                <div class="recent-content-item">
                                                    <a href="{{ tag.get_absolute_url }}">
                                                        <img src="/media/{{ tag.image }}" alt="{{ tag.title }}" width="70" height="67">
                                                    </a>
                                                    <div class="recent-text">
                                                        <h4>
                                                            <a href="{{ tag.get_absolute_url }}">
                                                                {{ tag.title }}
                                                            </a>
                                                        </h4>
                                                        <div class="single-item-comment-view">
                                                            <span><i class="zmdi zmdi-eye"></i>{{ tag.views }}</span>
                                                            {# <span><i class="zmdi zmdi-comments"></i>{{ comments.count }}</span> #}
                                                        </div>
                                                        <p>{{ tag.body|markdown|truncatewords_html:3 }}</p>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="single-sidebar-widget">
                                    <h4 class="title">Recent Post</h4>
                                    <div class="recent-content">
                                        {% for last_post in last_posts %}
                                            <div class="recent-content-item">
                                                <a href="{{ last_post.get_absolute_url }}">
                                                    <img src="/media/{{ last_post.image }}" alt="{{ last_post.title }}" width="70" height="67">
                                                </a>
                                                <div class="recent-text">
                                                    <h4><a href="{{ last_post.get_absolute_url }}">{{ last_post.title }}</a></h4>
                                                    <div class="single-item-comment-view">
                                                        <span><i class="zmdi zmdi-eye"></i>{{ last_post.views }}</span>
                                                        {# <span><i class="zmdi zmdi-comments"></i>{{ comments.count }}</span> #}
                                                    </div>
                                                    <p>{{ last_post.body|markdown|truncatewords_html:3 }}</p>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="single-sidebar-widget">
                                    <h4 class="title">Search by Tags</h4>
                                    <ul class="tags">
                                        {% for tags in all_tags  %}
                                            <li><a href="{% url 'blog:post_list_by_tag' tags.slug %}">{{tags.name}}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <!--End of News Details Area-->
        
    {% endblock %}

templates/blog/post/blog.html
{% extends "index/index.html" %}
{% load blog_tags %}

    {% block title %} {{ title }} {% endblock %}


    {% block content %}

        <!--Breadcrumb Banner Area Start-->
        <div class="breadcrumb-banner-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="breadcrumb-text">
                            {% if tag %}
                                <h1 class="text-center">Posts tagged with "{{ tag.name }}"</h1>
                                {% else %}
                                <h1 class="text-center">Maktab hayotiga oid yangiliklar</h1>
                            {% endif %}
                            <div class="breadcrumb-bar">
                                <ul class="breadcrumb text-center">
                                    <li><a href="{% url 'index:asosiy' %}">Bosh sahifa</a></li>
                                    <li>Yangiliklar</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--End of Breadcrumb Banner Area-->

        <!--Course Area Start-->
        <div class="course-area section-padding course-page">
            <div class="container">
                <div class="row">
                    {% for post in posts %}
                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="single-item">
                                <div class="single-item-image overlay-effect">
                                    <a href="{{ post.get_absolute_url }}">
                                        <img src="/media/{{ post.image }}" alt="{{ post.title }}" style="width:300px; height:211px;">
                                    </a>
                                </div>
                                <div class="single-item-text">
                                    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                                    <div class="single-item-text-info">
                                        <span>By: <span>{{ post.author }}</span></span>
                                        <span>Date: <span>{{ post.publish|date:"d.m.Y" }}</span></span>
                                    </div>
                                    <p>{{ post.body|markdown|truncatewords_html:10 }}</p>
                                    <div class="single-item-content">
                                       <div class="single-item-comment-view">
                                            <span><i class="zmdi zmdi-eye"></i>{{ post.views }}</span>
                                            <span><i class="zmdi zmdi-comments"></i>{{ comments.count }}</span>
                                        </div>
                                        <div class="single-item-rating">
                                           <i class="zmdi zmdi-star"></i>
                                           <i class="zmdi zmdi-star"></i>
                                           <i class="zmdi zmdi-star"></i>
                                           <i class="zmdi zmdi-star"></i>
                                           <i class="zmdi zmdi-star-half"></i>
                                           </div>
                                    </div>   
                                </div>
                                <div class="button-bottom">
                                    <a href="{{ post.get_absolute_url }}" class="button-default">Learn Now</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {% include "../pagination.html" with page=posts %}
                    </div>
                </div>
            </div>
        </div>
        <!--End of Course Area-->

    {% endblock %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %} 

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	
	<h1>{{ post.title }}</h1>
  	<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
  	{{ post.body | markdown }}

  	<p>
  		<a href="{% url 'blog:post_share' post.id %}">Share this post</a>
  	</p>
  	{# commentlar soni #}
  	{% with comments.count as total_comments %}
		<h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
	{% endwith %}

	{# comment #}
	{% for comment in comments %}
  		<div class="comment">
    		<p class="info">
				Comment {{ forloop.counter }} by {{ comment.name }}
      			{{ comment.created }}
    		</p>
    		{{ comment.body|linebreaks }}
  		</div>
		{% empty %}
  		<p>There are no comments yet.</p>
	{% endfor %}
	{# end comment #}

	{% if new_comment %}
		<h2>Your comment has been added.</h2>
		{% else %}
	  		<h2>Add a new comment</h2>
	  		<form action="." method="post">
	    		{{ comment_form.as_p }}
	    		{% csrf_token %}
	    		<p><input type="submit" value="Add comment"></p>
	  		</form>
	{% endif %}

	{% if similar_posts %}
		<p class="tags">
	  		Similar tags:
	    	{% for tag in similar_posts %}
	      		<a href="{{ tag.get_absolute_url }}">
	      			{{ tag.title }}
	      		</a>
	      		{% if not forloop.last %}, {% endif %}
	    	{% endfor %}
		</p>
	{% endif %}

{% endblock %}

templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>

templates/blog/post/list.html
{% extends 'blog/base.html' %} 
{% load blog_tags %}

{% block title %} My Blog {% endblock %}

{% block content %}
	<h1>My Blog</h1>
	
	{% if tag %}
		<h2>Posts tagged with "{{ tag.name }}"</h2>
	{% endif %}

	{% for post in posts %}
    	<h2>
      		<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    	</h2>
  		{# <p class="tags">Tags: {{ post.tags.all | join:", " }}</p> #}
  		<p class="tags">Tags:
	    	{% for tag in post.tags.all %}
	      		<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
	      			{{ tag.name }}
	      		</a>
	      		{% if not forloop.last %}, {% endif %}
	    	{% endfor %}
		</p>

    	<p class="date"> Published {{ post.publish | date:"d.m.Y" }} by {{ post.author }}</p>

    	{{ post.body|markdown|truncatewords_html:30 }}

  	{% endfor %}

	{% include "../pagination.html" with page=posts %}
	{# standart pagination #}
  	{# {% include "../pagination.html" with page=page_obj %} #}

{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}

  <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>

  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
  {% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  
  {% endif %}

{% endblock %}